server:
  port: 9101

spring:
  cloud:
    gateway:
      routes:
        - id: test
          uri: https://www.baidu.com
          predicates:
            - Query=url,baidu
        - id: qq
          uri: https://www.qq.com
          predicates:
            - Query=url,qq
