server:
  port: 9111
spring:
  application:
    name: consumer
  boot:
    admin:
      client:
        url: http://localhost:9002

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["*"]