server:
  port: 9111
spring:
  application:
    name: consumer

  boot:
    admin:
      client:
        url: http://localhost:9002

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: ["*"]
mybatis:
  mapper-locations: classpath:mapper/*.xml    # mapper映射文件位置
  type-aliases-package: com.sy.consumer    # 实体类所在的位置
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl   #用于控制台打印sql语句
