server:
  port: 9203
spring:

  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
  application:
    name: biz-web
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/seata?useSSL=false&serverTimezone=Asia/Shanghai
    username: root
    password: 123456
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

knife4j:
  enable: true
  setting:
    language: zh_cn
    swagger-model-name: 实体类列表
  gateway:
    strategy: discover
    discover:
      version: openapi3

#  enable-aggregation: true
#  nacos:
#    enable: true
#    service-url: http://127.0.0.1:8848/
#    routes:
#      - name: 订单服务
#        service-name: service-order
#        location: /v2/api-docs?group=default
