mdb:
  databases:
    - item:
        name: sso
        password: cRm@sH123
        user: crm
        db-type: mysql
        url: jdbc:mysql://db.crm.yinmatech.com:1433/data
        type: com.alibaba.druid.pool.DruidDataSource
        driver: com.mysql.cj.jdbc.Driver
        max: 10
        idle: 5
      mapper: 'com.ym.apps.mapper.common.*'
      name: sso
  desc: datasource