server:
  port: 9201
spring:
  application:
    name: biz-order
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.211:3306/cloud_alibaba?useSSL=false&serverTimezone=UTC
    username: root
    password: 113355
mybatis:
  mapper-locations: classpath*:mapper/*.xml
  configuration:
    log-impl: org.apache.ibatis.logging.slf4j.Slf4jImpl

