server:
  port: 9000

#logging:
#  level:
#    org.springframework.security: trace


spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.1.211:8106/oauth2?useSSL=false&serverTimezone=UTC
    username: root
    password: 123456

logging:
  level:
    root: info
    #    org.springframework.web.servlet.mvc.method.annotation.RequestMappingHandlerMapping: trace
    #    org.springframework.security: debug
    org.springframework.security.web.FilterChainProxy: trace # 过滤器执行顺序
    org.springframework.security.web.access.ExceptionTranslationFilter: trace #异常处理